

###
GET http://127.0.0.1:8000/electricgenerator/ HTTP/1.1


###
POST  http://localhost:8000/account/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "0751"
    , "password": 123
    }