// Mocks generated by Mockito 5.4.6 from annotations
// in moalidaty1/test/features/reciepts/services/reciept_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:moalidaty1/features/reciepts/models/model.dart' as _i2;
import 'package:moalidaty1/features/reciepts/repositories/repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReciept_0 extends _i1.SmartFake implements _i2.Reciept {
  _FakeReciept_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecieptRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecieptRepository extends _i1.Mock implements _i3.RecieptRepository {
  MockRecieptRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i5.Future<List<_i2.Reciept>> fetchReciepts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchReciepts, []),
            returnValue: _i5.Future<List<_i2.Reciept>>.value(<_i2.Reciept>[]),
          )
          as _i5.Future<List<_i2.Reciept>>);

  @override
  _i5.Future<_i2.Reciept> createReciept(_i2.Reciept? reciept) =>
      (super.noSuchMethod(
            Invocation.method(#createReciept, [reciept]),
            returnValue: _i5.Future<_i2.Reciept>.value(
              _FakeReciept_0(
                this,
                Invocation.method(#createReciept, [reciept]),
              ),
            ),
          )
          as _i5.Future<_i2.Reciept>);

  @override
  _i5.Future<void> destroyReciept(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#destroyReciept, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Reciept> updateReciept(_i2.Reciept? reciept) =>
      (super.noSuchMethod(
            Invocation.method(#updateReciept, [reciept]),
            returnValue: _i5.Future<_i2.Reciept>.value(
              _FakeReciept_0(
                this,
                Invocation.method(#updateReciept, [reciept]),
              ),
            ),
          )
          as _i5.Future<_i2.Reciept>);
}
